name: Release Drafter
on:
  push:
    branches:
      - headlining
  pull_request_target:
    branches:
      - headlining
    types:
      - opened
      - reopened
      - synchronize
      - edited
  workflow_dispatch:
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # env에 token 설정
